{"errorMessage":"Lambda process returned error status code: 1. Result: {}. Output:\n[eval]:1\nrequire(\"/tmp/localstack/zipfile.38a58b47/handler.js\").hello({},{\"function_name\": \"exemplo-lambda2-local-hello\", \"function_version\": \"$LATEST\", \"client_context\": null, \"invoked_function_arn\": \"arn:aws:lambda:us-east-1:000000000000:function:exemplo-lambda2-local-hello\", \"cognito_identity\": null, \"aws_request_id\": \"13e1318f-5647-4405-a840-ecf91fda6a93\", \"memory_limit_in_mb\": 1024, \"log_group_name\": \"/aws/lambda/exemplo-lambda2-local-hello\", \"log_stream_name\": \"2021/11/19/[1]b19a001b\"}).then(r => process.stdout.write(JSON.stringify(r)))\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ^\n\nTypeError: Cannot read property 'then' of undefined\n    at [eval]:1:489\n    at Script.runInThisContext (vm.js:134:12)\n    at Object.runInThisContext (vm.js:310:38)\n    at internal/process/execution.js:81:19\n    at [eval]-wrapper:6:22\n    at evalScript (internal/process/execution.js:80:60)\n    at internal/main/eval_string.js:27:3","errorType":"InvocationException","stackTrace":["  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 809, in run_lambda\n    result = LAMBDA_EXECUTOR.execute(\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 441, in execute\n    return do_execute()\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 431, in do_execute\n    return _run(func_arn=func_arn)\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 158, in wrapped\n    raise e\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 154, in wrapped\n    result = func(*args, **kwargs)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 418, in _run\n    raise e\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 414, in _run\n    result = self._execute(lambda_function, inv_context)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1361, in _execute\n    raise InvocationException(result, log_output)\n"]}
